import numpy as np

def sample_simplex(rng, d:int):
    '''
    Randomly uniformly (by volume) sample from the d-dimensional simplex
    '''
    # Dirichlet distribution samples from simplex with some weighting; weightings of 1 each give uniform;
    # Dirichlet is generated by Gamma dists with some choice of common scale and weightings from Dirichlet;
    # Gamma with scale 1 is just exponential
    x = rng.exponential(size=d)
    return x / np.sum(x)
